"use client";

import { useState } from "react";
import { Eye } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/Button";
import { Column, DataTable } from "@/components/ui/DataTable";
import { PageHeader } from "@/components/ui/PageHeader";
import { Pagination } from "@/components/ui/Pagination";
import { getApiErrorMessage } from "@/utils/apiError";
import { formatDate } from "@/utils/formatters";
import { useAuditoria } from "../hooks/useAuditoria";
import type { AuditoriaFinanceira } from "../services/auditoria.service";

export function AuditoriaList() { const { can } = useAuth(); const [modulo, setModulo] = useState(""); const [entidade, setEntidade] = useState(""); const [de, setDe] = useState(""); const [ate, setAte] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [selected, setSelected] = useState<AuditoriaFinanceira | null>(null); const query = useAuditoria({ modulo: modulo || undefined, entidade: entidade || undefined, de: de || undefined, ate: ate || undefined, page, pageSize }); const columns: Column<AuditoriaFinanceira>[] = [{ key: "dataAcao", label: "Data", render: (row) => formatDate(row.dataAcao) }, { key: "modulo", label: "Módulo" }, { key: "acao", label: "Ação" }, { key: "entidade", label: "Entidade" }, { key: "entidadeId", label: "ID" }, { key: "actions", label: "", className: "text-right", render: (row) => <Button variant="outline" onClick={() => setSelected(row)}><Eye size={15} className="mr-1" />Detalhes</Button> }]; if (!can("financeiro.auditoria.visualizar")) return null; return <div className="space-y-4 p-8"><PageHeader title="Auditoria Financeira" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Módulo" value={modulo} onChange={(event) => { setModulo(event.target.value); setPage(1); }} placeholder="Módulo" className="rounded-xl border border-[#d7f3ea] px-3 py-2" /><input aria-label="Entidade" value={entidade} onChange={(event) => { setEntidade(event.target.value); setPage(1); }} placeholder="Entidade" className="rounded-xl border border-[#d7f3ea] px-3 py-2" /><input aria-label="De" type="date" value={de} onChange={(event) => { setDe(event.target.value); setPage(1); }} className="rounded-xl border border-[#d7f3ea] px-3 py-2" /><input aria-label="Até" type="date" value={ate} onChange={(event) => { setAte(event.target.value); setPage(1); }} className="rounded-xl border border-[#d7f3ea] px-3 py-2" /></div><DataTable columns={columns} data={query.data?.data ?? []} loading={query.isLoading} error={query.isError ? getApiErrorMessage(query.error, "Erro ao carregar auditoria.") : null} onRetry={() => void query.refetch()} emptyMessage="Nenhum registro de auditoria encontrado." keyExtractor={(row) => row.id} /><Pagination page={page} totalPages={query.data?.totalPages ?? 0} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} /><AuditDetail entry={selected} onClose={() => setSelected(null)} /></div>; }

function AuditDetail({ entry, onClose }: { entry: AuditoriaFinanceira | null; onClose: () => void }) { if (!entry) return null; const parse = (value: string | null) => { if (!value) return "—"; try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Detalhes da auditoria #{entry.id}</h2><Button variant="outline" onClick={onClose}>Fechar</Button></div><dl className="mt-5 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Módulo</dt><dd>{entry.modulo}</dd></div><div><dt className="text-xs text-slate-500">Ação</dt><dd>{entry.acao}</dd></div><div><dt className="text-xs text-slate-500">Entidade</dt><dd>{entry.entidade} #{entry.entidadeId}</dd></div><div><dt className="text-xs text-slate-500">Data</dt><dd>{formatDate(entry.dataAcao)}</dd></div></dl><div className="mt-5 grid gap-4 md:grid-cols-2"><pre className="overflow-auto rounded-xl bg-slate-100 p-3 text-xs">{parse(entry.dadosAntes)}</pre><pre className="overflow-auto rounded-xl bg-slate-100 p-3 text-xs">{parse(entry.dadosDepois)}</pre></div>{entry.motivo && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">Motivo: {entry.motivo}</p>}</div></div>; }
