"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/Button";
import { FormField } from "@/components/ui/FormField";
import { useProdutos } from "../../produtos/hooks/useProdutos";
import { AjustarEstoqueSchema, RegistrarMovimentacaoSchema, type AjustarEstoqueFormData, type RegistrarMovimentacaoFormData } from "../schemas/movimentacao.schema";

export type MovimentacaoAction = "entrada" | "saida" | "sale" | "uso-interno" | "perda" | "ajuste";
interface Props { open: boolean; action: MovimentacaoAction; loading?: boolean; onClose: () => void; onSubmit: (data: RegistrarMovimentacaoFormData | AjustarEstoqueFormData) => Promise<void> | void; }
const labels: Record<MovimentacaoAction, string> = { entrada: "Registrar Entrada", saida: "Registrar Saída", sale: "Registrar Venda", "uso-interno": "Registrar Uso Interno", perda: "Registrar Perda", ajuste: "Ajustar Estoque" };
export function MovimentacaoDialog({ open, action, loading, onClose, onSubmit }: Props) { const { data } = useProdutos({ page: 1, pageSize: 100 }); const isAdjustment = action === "ajuste"; const registrar = useForm<RegistrarMovimentacaoFormData>({ resolver: zodResolver(RegistrarMovimentacaoSchema), values: { produtoId: 0, quantidade: 0, observacao: "" } }); const ajustar = useForm<AjustarEstoqueFormData>({ resolver: zodResolver(AjustarEstoqueSchema), values: { produtoId: 0, novaQuantidade: 0, observacao: "" } }); if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"><form onSubmit={isAdjustment ? ajustar.handleSubmit(onSubmit) : registrar.handleSubmit(onSubmit)} className="w-full max-w-md rounded-2xl border border-[#d7f3ea] bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">{labels[action]}</h2><div data-tutorial="movement-form-fields" className="mt-5 space-y-4"><div className="flex flex-col gap-2"><label htmlFor="movimentacao-produto" className="text-sm font-semibold">Produto</label><select id="movimentacao-produto" className="rounded-xl border border-[#d7f3ea] bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900" {...(isAdjustment ? ajustar.register("produtoId", { valueAsNumber: true }) : registrar.register("produtoId", { valueAsNumber: true }))}><option value={0}>Selecione</option>{data?.data.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></div>{isAdjustment ? <><FormField id="movimentacao-nova-quantidade" label="Nova quantidade" type="number" error={ajustar.formState.errors.novaQuantidade?.message} {...ajustar.register("novaQuantidade", { valueAsNumber: true })} /><FormField id="movimentacao-ajuste-observacao" label="Observação" required error={ajustar.formState.errors.observacao?.message} {...ajustar.register("observacao")} /></> : <><FormField id="movimentacao-quantidade" label="Quantidade" type="number" error={registrar.formState.errors.quantidade?.message} {...registrar.register("quantidade", { valueAsNumber: true })} /><FormField id="movimentacao-observacao" label="Observação" error={registrar.formState.errors.observacao?.message} {...registrar.register("observacao")} /></>}</div><div className="mt-6 flex gap-3"><Button type="button" variant="outline" onClick={onClose} disabled={loading}>Cancelar</Button><div data-tutorial="movement-form-save"><Button type="submit" loading={loading}>Salvar</Button></div></div></form></div>; }
